baseURL = "/"
languageCode = "en-us"
title = "tnflnt.co"
theme = "lekhiket"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 10 # articles per page

# Social Tags

# [[params.social]]
# name = "GitHub"
# icon = "github"
# url = "https://github.com/athul/archie"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Work ↗"
url = "https://tonyfolenta.com"
weight = 3


# Main menu Items

[[menu.footer]]
name = "Figma"
url = "https://www.figma.com/@tnflnt"
weight = 1

[[menu.footer]]
name = "Github"
url = "https://github.com/tnflnt"
weight = 2

[[menu.footer]]
name = "hi@tnflnt.co 📬"
url = "mailto:hi@tnflnt.co"
weight = 3