baseURL = "https://tnflnt.co/"
languageCode = "en-us"
title = "tnflnt.co"
theme = "lekhiket"

paginate = 5 # articles per page

[params]
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
description = "Hi! I'm Tony Folenta. I build design systems for digital products."
images = ["img/tnflnt-cover.png"]
title = "tnflnt.co"

# Main Menu Items

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

# [[menu.main]]
# name = "Work"
# url = "/work"
# weight = 2

[[menu.main]]
name = "About"
url = "/About"
weight = 3

# Footer Menu Items

[[menu.footer]]
name = "RSS 🗞"
url = "/index.xml"
weight = 1

[[menu.footer]]
name = "hi@tnflnt.co 📬"
url = "mailto:hi@tnflnt.co"
weight = 2